Revert "OpenPOWER: Limit User-Requested System Dumps"
This reverts commit 1ddb006b8bbb8294c402fe774e077528fd54d7fd.

Reported build failure on p10bmc machine

 ../git/dump-extensions/openpower-dumps/op_dump_util.cpp:85:30:
  error: too few arguments to function
 'openpower::dump::util::BIOSAttrValueType

Signed-off-by: Jayanth Othayoth <ojayanth@in.ibm.com>
Change-Id: Ia8f6fe6b096294ae9f478dcb44a28a95b878fddb