clang: openpower-dumps: fix file not found
Changes to address the issue with the auto-generated header file
`openpower_dumps_config.h` not being created during clang-tidy
context builds. This ensures the header file is generated without
relying on build flag settings.

'''
 error: 'dump-extensions/openpower-dumps/openpower_dumps_config.h' file not found [clang-diagnostic-error]
'''

Modified Meson build file to include openpower-dumps subdirectory
when clang-tidy is found

Change-Id: Icddec21d75cf55bf1a9b8fe3fed76d70b55a2257
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>