Empty strings issue for start and end time of dump header corrected
Problem: Sometimes start and end time strings of the dumpheader
can not be fetched/retrieved from the busctl commands and that
leads to failure in makedumptool parsing due to invalid dump
header.

Solution: Now if the start and end time strings are coming
blank for any reason we are setting them manually with the
current date time to avoid wrong dump header.

Test Results:

Before:

Feb 27 09:30:52 phosphor-dump-manager[6158]: date: invalid date '@'
Feb 27 09:30:52 phosphor-dump-manager[6141]: /usr/share/dreport.d/include.d/gendumpinfo:
line 45: [: -eq: unary operator expected
Feb 27 09:30:52 phosphor-dump-manager[6159]: date: invalid date '@'

Traceback (most recent call last):
File "/afs/awd.austin.ibm.com/projects/cte//tools/crondump/dev/makedump", line 762, in <module>
dumpfile = mdcommon.setHeaderFromManifestFile(manifestStream, dumpfile)
File "/afs/apd.pok.ibm.com/func/vlsi/cte/tools/crondump/dev/pymod/mdcommon.py", line 196, in setHeaderFromManifestFile
dumpfile.stats.actualTime = (yamlData['dump-end-time'] - yamlData['dump-start-time']).total_seconds()
TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'

After:

Mar 19 15:02:32 busctl[25515]: Failed to get property CompletedTime on interface xyz.openbmc_project.Common.Progress: Connection timed out
Mar 19 15:02:32 phosphor-dump-manager[25497]: Could not fetch start time for 20000007
Mar 19 15:02:32 phosphor-dump-manager[25497]: End time populated as: 2024-03-19 15:02:32

>>>> Writing output
>>>> Final Results
All output collected in: /tmp
 Dump File: /tmp/SYSDUMP.139B0B0.20000007.20240319145934-MDC.dump (153.93 MB)
 Stats File: /tmp/SYSDUMP.139B0B0.20000007.20240319145934-MDC.stats.bz2 (220.18 KB)
 Log File: /tmp/SYSDUMP.139B0B0.20000007.20240319145934-MDC.log (11.05 MB)
 Console File: /tmp/SYSDUMP.139B0B0.20000007.20240319145934-MDC.console (2.87 KB)
 HBMem File: /tmp/SYSDUMP.139B0B0.20000007.20240319145934-MDC.hbmem (64.00 MB)

Change-Id: I3319963b3cb61b34c0e51f7d37436e33e0fc7adb
Signed-off-by: Swarnendu Roy Chowdhury <swarnendu.roy.chowdhury@ibm.com>