clang:tidy host-transport-extensions Fix warnings
Fixed cppcoreguidelines-special-member-functions warning by defining
the move constructor and move assignment operator for the
PLDMInstanceManager class.

'''
 error: class 'PLDMInstanceManager' defines a non-default destructor, a copy constructor
 and a copy assignment operator but does not define a move constructor or a move assignment
 operator [cppcoreguidelines-special-member-functions,-warnings-as-errors]
'''

Change-Id: I959bed0787ee35de4aaeaf13ff53956198621493
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>