clang:openpower-dumps: fix defaulted-function-dele
Addressed the issue where the defaulted copy constructor is implicitly
deleted due to a base class having a deleted copy constructor.

'''
error: explicitly defaulted copy constructor is implicitly deleted [-Werror,-Wdefaulted-function-deleted]
'''

Change-Id: I4a944a9b4213142486be8e9b4bfe442dc01d1697
Signed-off-by: Jayanth Othayoth <ojayanth@gmail.com>